version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      storybook:
        patterns:
          - storybook
          - '@storybook/*'
      mantine:
        patterns:
          - mantine
          - '@mantine/*'
