---
version: 1
enabled: true
plugins:
  static_hosting:
    jest-coverage:
      metadata:
        name: Jest Coverage
      path: coverage/lcov-report
    jest-report:
      metadata:
        name: Jest Report
      path: tests/test-report.html
  job_runtime:
    enabled: true
